/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as RankingIndexRouteImport } from './routes/ranking/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community/': typeof CommunityIndexRoute
  '/games/': typeof GamesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/ranking/': typeof RankingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityIndexRoute
  '/games': typeof GamesIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/ranking': typeof RankingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community/': typeof CommunityIndexRoute
  '/games/': typeof GamesIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/ranking/': typeof RankingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/community/' | '/games/' | '/guides/' | '/profile/' | '/ranking/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/community' | '/games' | '/guides' | '/profile' | '/ranking'
  id:
    | '__root__'
    | '/'
    | '/community/'
    | '/games/'
    | '/guides/'
    | '/profile/'
    | '/ranking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RankingIndexRoute: typeof RankingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RankingIndexRoute: RankingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
